### ISSUE TITLE
Generate Model_

### ISSUE THREAD

**Issue by hendisantika** [adamzareba/company-structure-hibernate-cache#1]
Nice repo,

I want to ask you something.

How do you generate model_ (Company_, Employee_, ETC)?

Is there a way?

Thanks

**Comment by adamzareba** [comment]
Hi @hendisantika,

Thanks for the feedback.

I used [Hibernate JPA 2 Metamodel Generator](https://docs.jboss.org/hibernate/stable/jpamodelgen/reference/en-US/html_single/). To compile that classes I used maven plugin:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.7.0</version>
	<configuration>
		<source>${java.version}</source>
		<target>${java.version}</target>
		<showWarnings>true</showWarnings>
		<showDeprecation>true</showDeprecation>
		<compilerArguments>
			<processor>
				org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor,lombok.launch.AnnotationProcessorHider$AnnotationProcessor
			</processor>
		</compilerArguments>
	</configuration>
</plugin>
```

Thanks

**Comment by hendisantika** [comment]
OK. Then how do we run this project?
Because It always said error because of Company_ etc?
Thanks

**Comment by adamzareba** [comment]
To run the application execute following command in root directory:

```mvn package && java -jar target\company-structure-hibernate-cache-1.0-SNAPSHOT.jar```

(please check my today's commit, I added missing jackson library)

Thanks.

**Comment by hendisantika** [comment]
OK. Thanks.
I will try it first.
